spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://localhost:3306/neurogenomics_db
    username: root
    password: root


project:
  properties:
    upload-path: "/USER_DATA/USER_UPLOAD_DATA"
logging:
  config: classpath:logback-prod.xml
