spring:
  profiles:
    include:
      - core
      - db
      - web-core
      - default
server:
  port: 8080


---


spring:
  profiles: default
  application:
    name: today

project:
  properties:
    email-from: a@a.com
logging:
  config: classpath:logback-spring.xml
