spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useLegacyDatetimeCode=false&serverTimezone=Asia/Seoul
    username: root
    password: root
  application:
    name: db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.OracleDialect
      #      hibernate:
      #        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
      ##        current_session_context_class: thread
      #        jdbc:
      #          time_zone: UTC
      hibernate:
        #        use_sql_comments: true
        #        show_sql: true
        #        format_sql: true
        type: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
